language: rust
services:
  - docker

install:
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
  - cargo fmt -- --check

jobs:
  fast_finish: true
  include:
    - name: Dgraph 1.0 tests
      rust: stable
      before_install:
        - docker-compose -f docker-compose-1-0.yaml up -d
        - docker ps
      script:
        - cargo test --verbose -- --test-threads=1
