language: rust
services:
  - docker

matrix:
  fast_finish: true
  include:
    - name: clippy & fmt
      rust: stable
      before_install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - name: Dgraph 1.0 tests
      rust: stable
      before_install:
        - docker-compose -f docker-compose-1-0.yaml up -d
        - docker ps
      install:
        - cargo build
      script:
        - cargo test --verbose -- --test-threads=1
