[package]
name = "dgraph-tonic"
version = "0.1.0"
authors = ["Selmeci <selmeci.roman@gmail.com>"]
edition = "2018"
description = "A rust client for dGraph database"
readme = "README.md"
license = "MIT"
keywords = ["dgraph", "grpc", "async", "sync"]
repository = ""
homepage = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
env_logger = "0.6"
failure = "0.1"
futures = "0.3"
http = "0.2"
log = "0.4"
prost = "0.6"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "fs"] }
tonic = {version = "0.1", features = ["tls"]}

[dev-dependencies]
serde_derive = "1.0"

[build-dependencies]
tonic-build = "0.1"