[package]
name = "dgraph-tonic"
version = "0.1.1"
authors = ["Selmeci <selmeci.roman@gmail.com>"]
edition = "2018"
description = "A rust async client for dGraph database build with Tonic crate"
readme = "README.md"
license = "MIT"
keywords = ["dgraph", "grpc", "async"]
repository = "https://github.com/selmeci/dgraph-tonic"
homepage = "https://github.com/selmeci/dgraph-tonic"
exclude = [
    "build.rs"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
failure = "0.1"
futures = "0.3"
http = "0.2"
prost = "0.6"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
tonic = {version = "0.2", features = ["tls"]}

[dev-dependencies]
serde_derive = "1.0"

[build-dependencies]
tonic-build = "0.2"